---
  - name: Compile and package
    hosts: dev
    become: yes
    tasks:
      - name: Running mvn clean
        shell: "mvn -f /home/ubuntu/workspace/Compile_and_package_job/pom.xml clean install package"